### ISSUE TITLE
The virtual reality effect is basically a more simple version of the rewind effect

### ISSUE THREAD

**Issue by superfroggman** [NLferdiNL/Teardown-Chaos-Mod#10]
https://github.com/NLferdiNL/Teardown-Chaos-Mod/blob/56bfebba9449d57cbaff32ecf43bf0e512e3fae5/effects.lua#L2671

https://github.com/NLferdiNL/Teardown-Chaos-Mod/blob/56bfebba9449d57cbaff32ecf43bf0e512e3fae5/effects.lua#L798

**Comment by NLferdiNL** [comment]
Oh yeah you're right, alright I'll take it out again.
