### ISSUE TITLE
Teleport To A Random Location doesn't work when in a vehicle

### ISSUE THREAD

**Issue by superfroggman** [NLferdiNL/Teardown-Chaos-Mod#3]
https://github.com/NLferdiNL/Teardown-Chaos-Mod/blob/118190f04d20373c1a02cc7d93c66bd3e925d368/effects.lua#L447

Maybe it should teleport the vehicle too, but that could potentially put the vehicle inside of walls and stuff. It could also take you out of the vehicle if that is a problem.

**Comment by NLferdiNL** [comment]
Does that matter though? :P (Vehicles in wall)

**Comment by NLferdiNL** [comment]
On further note, I can't teleport the player to spawn in a vehicle in the edge case scenarios, pulling them out instead.
