### ISSUE TITLE
Same Effect twice

### ISSUE THREAD

**Issue by linusromland** [NLferdiNL/Teardown-Chaos-Mod#5]
I think you should add some check so you dont get the same effect twice in a row.

**Comment by NLferdiNL** [comment]
That shouldn't happen. Could you tell me which effect happened twice? Because similar effects, such as the gamespeed effects can overwrite each other. I am working on a fix for that.

**Comment by linusromland** [comment]
Just that you could get the same effect twice in a row. Like Teleport to random location twice. I just thought that would be a nice improvment

**Comment by NLferdiNL** [comment]
Looks like I'll need to check the logic for that again. But it shouldn't happen, there is a variable in the code to check for that.
But I'll have a look at it. Thanks

**Comment by NLferdiNL** [comment]
Are you running the latest version of the mod? Through workshop or this repo?

**Comment by NLferdiNL** [comment]
I have found the issue with this. Turns out I never assigned the variable to check last key. Thanks for letting me know!
